export const languagesSupport = {
    "js" : "javascript",
    "py" : "python",
    "java" : "java",
    "cpp" : "cpp",
    "c" : "c",
    "cs" : "csharp",
    "rb" : "ruby",
    "php" : "php",
    "go" : "go",
    "swift" : "swift",
    "kt" : "kotlin",
    "ts" : "typescript",
    "sql" : "sql",
    "xml" : "xml",
    "html" : "html",
    "css" : "css",
    "json" : "json",
    "md" : "markdown",
    "yml" : "yaml",
    "sh" : "shell",
}